name: Release CI

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Inject Version from Tag
        run: npx gitv
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
